### ISSUE TITLE
Running via Fargate Service

### ISSUE THREAD

**Issue by moltar** [moia-oss/bastion-host-forward#171]
I really like the idea of using SSM sessions and haproxy together!

Previously I was using some hand-rolled SSH solution that used tunneling, wasn't great.

I was wondering if instead of using EC2, would it be possible to use Fargate Service?

Would be easier to just use an existing an official haproxy image.

Are the costs much different?

Also, was thinking that maybe with either EC2 or Fargate, it'd be possible to start/stop the service via some sort of CLI, or even detecting the connection? Or maybe even some SSM event?

Not sure, just throwing some ideas out there in case you know more :)

**Comment by moltar** [comment]
To answer my own question re pricing: https://calculator.aws/#/estimate?id=806c667aa48d9f8fd25768f78e507ee1a6ade255

Smallest Fargate Service will run at ~  **9.01 USD** per month.

**Comment by snowiow** [comment]
Hi there,
yes we actually already thought about something like that. Less because of the cost perspective, because the current solution is cheaper: https://calculator.aws/#/estimate?id=d67bdffee88a66558f0baff5a71026f708752327 but because we don't have to care about security updates on the ec2 instances, since once started they are normally long running for us. 

Also there is this blog post elaborating on the fargate bastion host: https://blog.bruceleeharrison.com/2021/03/02/aws-ecs-fargate-bastion-host/ which I only skimmed over a bit so far. 

Another quick win in the costs department could be to use the new t4g.nano instance. Then the instance would only cost 6.08$ in us-east-1. However I'm not sure if it's available in all regions already and if all the software is running on ARM.

**Comment by moltar** [comment]
I am wondering though if there is a way to trigger ec2 or fargate to start stop based on event. But then I don't know if the SSM will timeout or wait for it to boot.

**Comment by snowiow** [comment]
I think there is no connection possible, because the server where SSM is doesn't exist yet, but I didn't test it myself so far.

All of these event based things should be possible with CloudWatch Events / EventBridge. Maybe you also need a Lambda Function which is triggerd by the CloudWatch Event and starts or stops the instance.

**Comment by moltar** [comment]
Ok, I looked at the docs and nothing obvious jumps out. Will close the issue for now, as it doesn't seem actionable at this point. But if anything, we can still continue the conversation here. Cheers!
